# Generated by Django 4.2.6 on 2024-05-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=12)),
            ],
        ),
    ]
