# Generated by Django 4.2.6 on 2024-05-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Biblioteca',
        ),
    ]
