# Generated by Django 4.2.6 on 2024-05-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atividades_interativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividades_interativas', models.CharField(max_length=200)),
            ],
        ),
    ]
