# Generated by Django 4.2.6 on 2024-05-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.CharField(max_length=100)),
                ('idCriador', models.CharField(max_length=150)),
                ('CPF', models.CharField(default='-', max_length=11, primary_key=True, serialize=False, unique=True)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
