# Generated by Django 4.2.6 on 2024-05-22 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_comentario_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='idade',
        ),
        migrations.AddField(
            model_name='comentario',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
